### ISSUE TITLE
background.js is not executed in the production build

### ISSUE THREAD

**Issue by lllllllqw** [tjx666/awesome-chrome-extension-boilerplate#10]

**Comment by lllllllqw** [comment]
I delete the 'optimization' option in webpack.prod.ts and it works

**Comment by lllllllqw** [comment]
Is there any better plan ?

**Comment by tjx666** [comment]
This is because background.js doesn't load webpack runtime script `/js/runtime.js`. It's not like`index.html` can import by script tag.

![screenshot_2020-06-15_23-15-13](https://user-images.githubusercontent.com/41773861/84674992-3b021400-af5e-11ea-9a21-68ec50d8d14b.png)

I fix it by remove config `optimization.runtimeChunk`.
